/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.User.KhoHang;

import Controller.AccountController;
import Controller.ProductController;
import Controller.SupplierController;
import Model.Account;
import Model.Supplier;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell G3
 */
public class ViewKhoHang extends javax.swing.JPanel {

    /**
     * Creates new form ViewKhoHang
     */
    
    ArrayList<Supplier> list = new ArrayList<>();
    ArrayList<String> listIdAccount = new ArrayList<>();
    ArrayList<String> listIdProduct = new ArrayList<>();
    Account accountUser ;
    int id = Integer.valueOf(SupplierController.getList().get(SupplierController.getList().size()-1).getIdSupplier()) + 1;
    
    public ViewKhoHang() {
        initComponents();
    }
    
    public ViewKhoHang(Account account) {
        initComponents();
        HienThi();
        accountUser = account;
        ViewTT.setVisible(false);
        listIdAccount = AccountController.getListId();
        listIdProduct = ProductController.getListId();
        txtIdNV.setText(accountUser.getIdUser());
        for (String idPro : listIdProduct) {
            IdProduct.addItem(idPro);
        }
        NameNCC.addItem("All");
        for (int i = 0; i < list.size(); i++) {
            String s = list.get(i).getNameSupplier();
                int count = 0;
                int [] index = new int[list.size()];
            for (int j = 0; j < list.size(); j++) {
                if (s.equals(list.get(j).getNameSupplier())) {
                    index[count] = j;
                    count = count+1;
                }
            }
            if (count <= 1) {
                NameNCC.addItem(s);
            }else {
                if (index[0] == i) {
                    NameNCC.addItem(s);
                }
            }
        }
    }
    
    public void HienThi(){
        list = SupplierController.getList();
        DefaultTableModel model = (DefaultTableModel) SupplierTable.getModel();
        model.setRowCount(0);
        for (Supplier supplier : list) {
            Object[] obj_model = new Object[]{ supplier.getIdSupplier(),supplier.getNameSupplier(),supplier.getNumber(),
                supplier.getPrice(),supplier.getIdUser(),supplier.getIdProduct(),supplier.getCreated_at()
            };
            model.addRow(obj_model);
        }
    }
    public Boolean ExamInput(){
        boolean check = true;
        if (txtName.equals("") || txtPhone.equals("") || txtPrice.equals("")) {
            check = false;
        }
        if (IdProduct.getSelectedItem()== null) {
            check = false;
        }
        return check;
    }
    
    public void reset(){
        txtName.setText("");
        txtPhone.setText("");
        txtPrice.setText("");
        txtId.setText("");
        txtIdNV.setText(accountUser.getIdUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addProduct = new rsbuttom.RSButtonMetro();
        editProduct = new rsbuttom.RSButtonMetro();
        searchProduct = new rsbuttom.RSButtonMetro();
        NameNCC = new javax.swing.JComboBox<>();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SupplierTable = new javax.swing.JTable();
        ViewTT = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        off = new javax.swing.JButton();
        Canel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        IdProduct = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        txtIdNV = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        date_chooser = new com.toedter.calendar.JDateChooser();
        searchDate = new rsbuttom.RSButtonMetro();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel9.setBackground(new java.awt.Color(252, 182, 6));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/warehouse1.png"))); // NOI18N
        jLabel6.setText("KHO HÀNG");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        addProduct.setBackground(new java.awt.Color(252, 182, 6));
        addProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        addProduct.setText("THÊM MỚI");
        addProduct.setColorHover(new java.awt.Color(255, 153, 0));
        addProduct.setColorNormal(new java.awt.Color(252, 182, 6));
        addProduct.setColorPressed(new java.awt.Color(252, 182, 6));
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        editProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Actions-document-edit-icon.png"))); // NOI18N
        editProduct.setText("CHỈNH SỬA");
        editProduct.setColorHover(new java.awt.Color(255, 153, 0));
        editProduct.setColorNormal(new java.awt.Color(252, 182, 6));
        editProduct.setColorPressed(new java.awt.Color(252, 182, 6));
        editProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductActionPerformed(evt);
            }
        });

        searchProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon.png"))); // NOI18N
        searchProduct.setText("Tìm Kiếm");
        searchProduct.setColorHover(new java.awt.Color(255, 153, 0));
        searchProduct.setColorNormal(new java.awt.Color(252, 182, 6));
        searchProduct.setColorPressed(new java.awt.Color(252, 182, 6));
        searchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductActionPerformed(evt);
            }
        });

        NameNCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameNCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NameNCCItemStateChanged(evt);
            }
        });
        NameNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameNCCActionPerformed(evt);
            }
        });

        rSButtonMetro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        rSButtonMetro4.setText("Làm Mới");
        rSButtonMetro4.setColorHover(new java.awt.Color(255, 153, 0));
        rSButtonMetro4.setColorNormal(new java.awt.Color(252, 182, 6));
        rSButtonMetro4.setColorPressed(new java.awt.Color(252, 182, 6));
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(editProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 871, Short.MAX_VALUE)
                .addComponent(NameNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(252, 182, 6));

        SupplierTable.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SupplierTable.setForeground(new java.awt.Color(43, 121, 150));
        SupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Nhà Cung Cấp", "Số điện thoại", "Giá Nhập", "Mã Nhân Viên", "Mã Sản Phẩm", "Ngày Nhập Kho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SupplierTable.setGridColor(new java.awt.Color(43, 121, 150));
        SupplierTable.setSelectionBackground(new java.awt.Color(37, 150, 190));
        SupplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(SupplierTable);

        ViewTT.setBackground(new java.awt.Color(255, 255, 255));
        ViewTT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Title.setForeground(new java.awt.Color(43, 121, 150));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 121, 150));
        jLabel3.setText("Mã Đơn");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(43, 121, 150));
        jLabel4.setText("Nhà Cung Cấp");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(43, 121, 150));
        jLabel5.setText("Số Điện Thoại");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(43, 121, 150));
        jLabel7.setText("Giá Nhập");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(43, 121, 150));
        jLabel8.setText("Ngày đăng kí");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("VNĐ");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        off.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        off.setText("...");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        Canel.setBackground(new java.awt.Color(252, 182, 6));
        Canel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Canel.setText("Thoát");
        Canel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CanelMouseClicked(evt);
            }
        });
        Canel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(43, 121, 150));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mã NV");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(43, 121, 150));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Mã SP");

        txtIdNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout ViewTTLayout = new javax.swing.GroupLayout(ViewTT);
        ViewTT.setLayout(ViewTTLayout);
        ViewTTLayout.setHorizontalGroup(
            ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewTTLayout.createSequentialGroup()
                .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewTTLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewTTLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ViewTTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewTTLayout.createSequentialGroup()
                        .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewTTLayout.createSequentialGroup()
                                .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(59, Short.MAX_VALUE))
                            .addGroup(ViewTTLayout.createSequentialGroup()
                                .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ViewTTLayout.createSequentialGroup()
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel9))
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(ViewTTLayout.createSequentialGroup()
                        .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewTTLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Canel))
                            .addGroup(ViewTTLayout.createSequentialGroup()
                                .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewTTLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(92, 92, 92)
                                        .addComponent(IdProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ViewTTLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(92, 92, 92)
                                        .addComponent(txtIdNV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewTTLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(off)
                .addGap(154, 154, 154))
        );
        ViewTTLayout.setVerticalGroup(
            ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewTTLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Title)
                .addGap(29, 29, 29)
                .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewTTLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewTTLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(off)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Canel)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(713, Short.MAX_VALUE)
                .addComponent(ViewTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(405, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel4.setBackground(new java.awt.Color(252, 182, 6));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        date_chooser.setBackground(new java.awt.Color(255, 255, 255));
        date_chooser.setForeground(new java.awt.Color(255, 0, 0));
        date_chooser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        date_chooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_chooserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                date_chooserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                date_chooserMouseExited(evt);
            }
        });

        searchDate.setBackground(new java.awt.Color(252, 182, 6));
        searchDate.setText("Chọn ngày");
        searchDate.setColorHover(new java.awt.Color(255, 153, 0));
        searchDate.setColorNormal(new java.awt.Color(252, 182, 6));
        searchDate.setColorPressed(new java.awt.Color(252, 182, 6));
        searchDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(searchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void CanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanelActionPerformed
        reset();
        ViewTT.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_CanelActionPerformed

    private void CanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanelMouseClicked

    }//GEN-LAST:event_CanelMouseClicked

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed

        if (off.getText().equals("Nhập")){
            boolean test = ExamInput();
            if (test == false) {
                JOptionPane.showMessageDialog(this, "Bạn đã nhập thiếu thông tin","Invalidation",JOptionPane.ERROR_MESSAGE);
            }
            else{
                String nameSupplier = txtName.getText();
                String number = txtPhone.getText();
                Double price = Double.valueOf(txtPrice.getText());
                String idProduct = (String)IdProduct.getSelectedItem();
                String idUser = txtIdNV.getText();
                String created_at = String.valueOf(LocalDate.now());
                Supplier supplier = new Supplier(nameSupplier, number, price, idProduct, idUser, created_at);
                int kq = SupplierController.AddSupplier(supplier);
                if (kq > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm vào kho hàng!");
                    HienThi();
                }else{
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!");
                }

            }
            reset();
            ViewTT.setVisible(false);

        }
        else{
            boolean test = ExamInput();
            if (test == false) {
                JOptionPane.showMessageDialog(this, "Bạn đã nhập thiếu thông tin","Invalidation",JOptionPane.ERROR_MESSAGE);
            }
            else{
                Supplier supplier = new Supplier(txtName.getText(), txtPhone.getText(), Double.valueOf(txtPrice.getText()),(String)IdProduct.getSelectedItem(),txtIdNV.getText());
                if (SupplierController.updateSupplier(Integer.parseInt(txtId.getText()),supplier) > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công","Invalidation",JOptionPane.INFORMATION_MESSAGE);
                    HienThi();
                }else{
                    JOptionPane.showMessageDialog(this, "Cập nhật thất bại","Invalidation",JOptionPane.ERROR_MESSAGE);
                }
            }
            reset();
        }
    }//GEN-LAST:event_offActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void searchDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDateActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(date_chooser.getDate());
        ArrayList<Supplier> listSuppliers = SupplierController.searchDate(date);
        if (listSuppliers.size() > 0) {
            DefaultTableModel model = (DefaultTableModel) SupplierTable.getModel();
            model.setRowCount(0);
            for (Supplier supplier : listSuppliers) {
                Object[] obj_model = new Object[]{ supplier.getIdSupplier(),supplier.getNameSupplier(),supplier.getNumber(),
                    supplier.getPrice(),supplier.getIdUser(),supplier.getIdProduct(),supplier.getCreated_at()
                };
                model.addRow(obj_model);
            }
        }else{
            DefaultTableModel model = (DefaultTableModel) SupplierTable.getModel();
            model.setRowCount(0);
        }
    }//GEN-LAST:event_searchDateActionPerformed

    private void date_chooserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_chooserMouseExited

    }//GEN-LAST:event_date_chooserMouseExited

    private void date_chooserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_chooserMouseEntered

    }//GEN-LAST:event_date_chooserMouseEntered

    private void date_chooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_chooserMouseClicked

    }//GEN-LAST:event_date_chooserMouseClicked

    private void SupplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierTableMouseClicked
        Object row[] = new Object[7];
        for (int i = 0; i < 7; i++) {
            row[i] = SupplierTable.getValueAt(SupplierTable.getSelectedRow(), i);
        }
        txtId.setText(row[0].toString());
        txtName.setText(row[1].toString());
        txtPhone.setText(row[2].toString());
        txtPrice.setText(row[3].toString());
        IdProduct.setSelectedItem(row[5]);
        txtIdNV.setText(row[4].toString());
        txtDate.setText(row[6].toString());
        ViewTT.setVisible(true);
        off.setVisible(false);
    }//GEN-LAST:event_SupplierTableMouseClicked

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed

        reset();
        ViewTT.setVisible(false);
        HienThi();
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void NameNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameNCCActionPerformed
        String Name = (String)NameNCC.getSelectedItem();
        if (Name.equals("All") == false) {
            ArrayList<Supplier> listSuppliers = SupplierController.searchNameSupplier(Name);
            if (listSuppliers.size() > 0) {
                DefaultTableModel model = (DefaultTableModel) SupplierTable.getModel();
                model.setRowCount(0);
                for (Supplier supplier : listSuppliers) {
                    Object[] obj_model = new Object[]{ supplier.getIdSupplier(),supplier.getNameSupplier(),supplier.getNumber(),
                        supplier.getPrice(),supplier.getIdUser(),supplier.getIdProduct(),supplier.getCreated_at()
                    };
                    model.addRow(obj_model);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy đơn hàng");
                HienThi();
            }
        }
    }//GEN-LAST:event_NameNCCActionPerformed

    private void NameNCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NameNCCItemStateChanged

    }//GEN-LAST:event_NameNCCItemStateChanged

    private void searchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductActionPerformed
        String id = JOptionPane.showInputDialog("Nhập mã đơn hàng");
        Supplier supplier = SupplierController.searchSupplier(id);
        if (supplier != null) {
            DefaultTableModel model = (DefaultTableModel) SupplierTable.getModel();
            model.setRowCount(0);
            Object[] obj_model = new Object[]{supplier.getIdSupplier(),supplier.getNameSupplier(),supplier.getNumber(),
                supplier.getPrice(),supplier.getIdUser(),supplier.getIdProduct(),supplier.getCreated_at()};
            model.addRow(obj_model);
        }else{
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm");
            HienThi();
        }
    }//GEN-LAST:event_searchProductActionPerformed

    private void editProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductActionPerformed
        String id = JOptionPane.showInputDialog("Mã đơn hàng");
        try {
            Integer.parseInt(id);
            Supplier supplier = SupplierController.searchSupplier(id);
            if (supplier == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy đơn hàng","Invalidation",JOptionPane.ERROR_MESSAGE);
            }else{
                txtId.setText(String.valueOf(supplier.getIdSupplier()));
                txtName.setText(supplier.getNameSupplier());
                txtPhone.setText(supplier.getNumber());
                txtPrice.setText(String.valueOf(supplier.getPrice()));
                IdProduct.setSelectedItem(supplier.getIdProduct());
                txtIdNV.setText(supplier.getIdUser());
                txtDate.setText(supplier.getCreated_at());
                ViewTT.setVisible(true);
                off.setVisible(true);
                Title.setText("Điền Thông Tin Khách Hàng");
                off.setText("Sửa");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập số","Invalidation",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editProductActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        reset();
        txtId.setText(String.valueOf(id));
        txtPrice.setText("0.0");
        txtDate.setText(String.valueOf(LocalDate.now()));
        ViewTT.setVisible(true);
        Title.setText("Điền Thông Tin Hàng Hoá");
        off.setVisible(true);
        off.setText("Nhập");
        txtIdNV.setText(accountUser.getIdUser());
    }//GEN-LAST:event_addProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Canel;
    private javax.swing.JComboBox<String> IdProduct;
    private javax.swing.JComboBox<String> NameNCC;
    private javax.swing.JTable SupplierTable;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel ViewTT;
    private rsbuttom.RSButtonMetro addProduct;
    private com.toedter.calendar.JDateChooser date_chooser;
    private rsbuttom.RSButtonMetro editProduct;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton off;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro searchDate;
    private rsbuttom.RSButtonMetro searchProduct;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtIdNV;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
