/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SanPham;

import Controller.CategoryControlller;
import Controller.ProductController;
import Model.Category;
import Model.Product;
import View.Admin.SanPham.Category_TL;
import View.SanPham.SuaSP;
import View.SanPham.ViewSP;
import View.SanPham.ThemSP;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class pnlSanPham extends javax.swing.JPanel {

   
    ArrayList<Product> listProduct = new ArrayList<>();
    ArrayList<Category> listCategory = new ArrayList<>();
    
    public pnlSanPham() {
        initComponents();
        HienThi();
    }
    
    public void HienThi(){
        listProduct = ProductController.getList();
        DefaultTableModel model = (DefaultTableModel) TableProduct.getModel();
        model.setRowCount(0);
        for (Product pro : listProduct) {
            Object[] obj_model = new Object[]{pro.getIdProduct(),pro.getNameProduct(),pro.getDescriptionProduct(),
                pro.getSize(),pro.getIdCategory(),pro.getStatusProduct(),pro.getPriceProduct(),pro.getCreated_at(),pro.getAvatar()
            };
            model.addRow(obj_model);
        }
        listCategory = CategoryControlller.getList();
        maTL.addItem("All");
        for (int i = 0; i < listCategory.size(); i++) {
            maTL.addItem(listCategory.get(i).getFullnameCategory());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProduct = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        editProduct = new rsbuttom.RSButtonMetro();
        deleteProduct = new rsbuttom.RSButtonMetro();
        searchProduct = new rsbuttom.RSButtonMetro();
        maTL = new javax.swing.JComboBox<>();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        addProduct = new rsbuttom.RSButtonMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Category = new rsbuttom.RSButtonMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(252, 182, 6));

        TableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên Sản Phẩm", "Mô Tả", "Size", "Thể Loại", "Tình Trạng", "Giá", "Ngày Bán", "Avatar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableProduct.setGridColor(new java.awt.Color(43, 121, 150));
        TableProduct.setRowHeight(28);
        TableProduct.setSelectionBackground(new java.awt.Color(37, 150, 190));
        TableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProduct);
        if (TableProduct.getColumnModel().getColumnCount() > 0) {
            TableProduct.getColumnModel().getColumn(0).setMaxWidth(70);
            TableProduct.getColumnModel().getColumn(1).setMaxWidth(200);
            TableProduct.getColumnModel().getColumn(2).setMaxWidth(380);
            TableProduct.getColumnModel().getColumn(3).setMaxWidth(50);
            TableProduct.getColumnModel().getColumn(4).setMaxWidth(120);
            TableProduct.getColumnModel().getColumn(5).setMaxWidth(130);
            TableProduct.getColumnModel().getColumn(6).setMaxWidth(70);
            TableProduct.getColumnModel().getColumn(7).setMaxWidth(100);
            TableProduct.getColumnModel().getColumn(8).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        editProduct.setBackground(new java.awt.Color(252, 182, 6));
        editProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Actions-document-edit-icon.png"))); // NOI18N
        editProduct.setText("CHỈNH SỬA");
        editProduct.setColorHover(new java.awt.Color(255, 153, 0));
        editProduct.setColorNormal(new java.awt.Color(252, 182, 6));
        editProduct.setColorPressed(new java.awt.Color(252, 182, 6));
        editProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductActionPerformed(evt);
            }
        });

        deleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/del_2.png"))); // NOI18N
        deleteProduct.setText("XOÁ");
        deleteProduct.setColorHover(new java.awt.Color(255, 153, 0));
        deleteProduct.setColorNormal(new java.awt.Color(252, 182, 6));
        deleteProduct.setColorPressed(new java.awt.Color(252, 182, 6));
        deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductActionPerformed(evt);
            }
        });

        searchProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon.png"))); // NOI18N
        searchProduct.setText("TÌM KIẾM");
        searchProduct.setColorHover(new java.awt.Color(255, 153, 0));
        searchProduct.setColorNormal(new java.awt.Color(252, 182, 6));
        searchProduct.setColorPressed(new java.awt.Color(252, 182, 6));
        searchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductActionPerformed(evt);
            }
        });

        maTL.setBackground(new java.awt.Color(255, 153, 0));
        maTL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        maTL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maTLItemStateChanged(evt);
            }
        });
        maTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maTLActionPerformed(evt);
            }
        });

        rSButtonMetro4.setBackground(new java.awt.Color(252, 182, 6));
        rSButtonMetro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        rSButtonMetro4.setText("LÀM MỚI");
        rSButtonMetro4.setColorHover(new java.awt.Color(255, 153, 0));
        rSButtonMetro4.setColorNormal(new java.awt.Color(252, 182, 6));
        rSButtonMetro4.setColorPressed(new java.awt.Color(252, 182, 6));
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });

        addProduct.setBackground(new java.awt.Color(252, 182, 6));
        addProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        addProduct.setText("THÊM MỚI");
        addProduct.setColorHover(new java.awt.Color(255, 153, 0));
        addProduct.setColorNormal(new java.awt.Color(252, 182, 6));
        addProduct.setColorPressed(new java.awt.Color(252, 182, 6));
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(editProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(maTL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maTL, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(252, 182, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cup-Cake-icon.png"))); // NOI18N
        jLabel1.setText("Sản Phẩm");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Category.setBackground(new java.awt.Color(204, 147, 2));
        Category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Tick.png"))); // NOI18N
        Category.setText("Thể Loại");
        Category.setColorHover(new java.awt.Color(255, 153, 0));
        Category.setColorNormal(new java.awt.Color(252, 182, 6));
        Category.setColorPressed(new java.awt.Color(252, 182, 6));
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1120, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
       ThemSP addSP = new ThemSP();
       addSP.setVisible(true);
       HienThi();
    }//GEN-LAST:event_addProductActionPerformed

    private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductActionPerformed
        String idProduct = (String) TableProduct.getValueAt(TableProduct.getSelectedRow(), 0);
        if (JOptionPane.showConfirmDialog(this, "Xoá sản phẩm ?","Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int kq = ProductController.deleteProduct(idProduct);
            if (kq > 0) {
                HienThi();
            }else{
                JOptionPane.showMessageDialog(this, "Xoá sản phẩm lỗi!");
                HienThi();
            }
        }
    }//GEN-LAST:event_deleteProductActionPerformed

    private void searchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductActionPerformed
        String ipSP = JOptionPane.showInputDialog("Nhập mã sản phẩm");
        Product pro = ProductController.searchProduct(ipSP);
        if (pro != null) {
            DefaultTableModel model = (DefaultTableModel) TableProduct.getModel();
        model.setRowCount(0);
            Object[] obj_model = new Object[]{pro.getIdProduct(),pro.getNameProduct(),pro.getDescriptionProduct(),
                pro.getSize(),pro.getIdCategory(),pro.getStatusProduct(),pro.getPriceProduct(),pro.getCreated_at(),pro.getAvatar()
            };
            model.addRow(obj_model);
        }else{
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm!");
                HienThi();
        }
    }//GEN-LAST:event_searchProductActionPerformed

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        maTL.setSelectedItem("All");
        HienThi();
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void maTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maTLActionPerformed
        String ma = (String)maTL.getSelectedItem();
        for (Category listCategory : listCategory) {
            if (ma.equals(listCategory.getFullnameCategory())) {
                ma = listCategory.getIdCategory();
                break;
            }
        }
        if (ma.equals("All") == false) {
            ArrayList<Product> list = ProductController.searchProduct_Ma(ma);
            DefaultTableModel model = (DefaultTableModel) TableProduct.getModel();
                model.setRowCount(0);
            for (Product pro : list) {
                Object[] obj_model = new Object[]{pro.getIdProduct(),pro.getNameProduct(),pro.getDescriptionProduct(),
                    pro.getSize(),pro.getIdCategory(),pro.getStatusProduct(),pro.getPriceProduct(),pro.getCreated_at(),pro.getAvatar()
                };
            model.addRow(obj_model);
            }
        }
    }//GEN-LAST:event_maTLActionPerformed

    private void maTLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maTLItemStateChanged
        
    }//GEN-LAST:event_maTLItemStateChanged

    private void TableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProductMouseClicked
        Object row[] = new Object[9];
        for (int i = 0; i < 9; i++) {
            row[i] = TableProduct.getValueAt(TableProduct.getSelectedRow(), i);
        }
        Product product = new Product(row[0].toString(),row[1].toString(),row[2].toString(), (byte[]) row[8],row[3].toString(),
                row[4].toString(),row[5].toString(),Double.valueOf(row[6].toString()),row[7].toString());
        ViewSP viewSP = new ViewSP(product);
        viewSP.setVisible(true);
        
        
    }//GEN-LAST:event_TableProductMouseClicked

    private void editProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductActionPerformed
        String ipSP = JOptionPane.showInputDialog("Nhập mã sản phẩm");
        Product product = ProductController.searchProduct(ipSP);
        if (product!= null) {
            SuaSP suaSP = new SuaSP(product);
        suaSP.setVisible(true);
        }else{
           JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm!");

        }
    }//GEN-LAST:event_editProductActionPerformed

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        Category_TL cate = new Category_TL();
        cate.setVisible(true);
    }//GEN-LAST:event_CategoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro Category;
    private javax.swing.JTable TableProduct;
    private rsbuttom.RSButtonMetro addProduct;
    private rsbuttom.RSButtonMetro deleteProduct;
    private rsbuttom.RSButtonMetro editProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> maTL;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro searchProduct;
    // End of variables declaration//GEN-END:variables
}
