/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.User.BanHang;

import Controller.ChiTietController;
import Controller.CustomerController;
import Controller.OrderProductController;
import Controller.ProductController;
import Model.Account;
import Model.ChiTiet;
import Model.Customer;
import Model.OrderProduct;
import Model.Product;
import Model.sale;
import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell G3
 */
public class ViewOrder extends javax.swing.JFrame {

    /**
     * Creates new form ViewOrder
     */
    
    Account accountUser = null;
    String phoneCustomer = null;
    ArrayList<ChiTiet> listCart = new ArrayList<>();
    ArrayList<Customer> listCustomers = CustomerController.getList();
    ArrayList<Product> listProductTM = new ArrayList<>();
    ArrayList<Product> listProduct = new ArrayList<>();
    
    
    public ViewOrder() {
        initComponents();
        this.setLocationRelativeTo(this);
        HienThi("BK");
        Category.setVisible(true);
        Order.setVisible(true);
        txtTongHD.setText("0.0");
        listProduct = ProductController.getList();
        CapNhat.setVisible(false);
        EditSoLuong.setVisible(false);
        EdittxtID1.setVisible(false);
        EditDG.setVisible(false);
        Edit1.setVisible(false);
    }
    
    public ViewOrder(Account account) {
        initComponents();
        listProduct = ProductController.getList();
        accountUser = account;
        this.setLocationRelativeTo(this);
        HienThi("BK");
        txtTenNV.setText(account.getFullName());
        Category.setVisible(true);
        Order.setVisible(true);
        txtTongHD.setText("0.0");
        CapNhat.setVisible(false);
        EditSoLuong.setVisible(false);
        EdittxtID1.setVisible(false);
        EditDG.setVisible(false);
        Edit1.setVisible(false);
        ht1.setVisible(false);
        ht2.setVisible(false);
        ht3.setVisible(false);
    }
    
    public void HienThi(String idCategory){
        listProductTM = ProductController.searchProduct_Ma(idCategory);
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
        for (Product pro : listProductTM) {
            Object[] obj_model = new Object[]{pro.getIdProduct(),pro.getNameProduct(),
                pro.getSize(),pro.getStatusProduct(),pro.getPriceProduct(),pro.getAvatar()
            };
            model.addRow(obj_model);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HoaDon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDHD = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JLabel();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        jLabel6 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSale = new javax.swing.JLabel();
        txtIDHD4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTongHD = new javax.swing.JLabel();
        txtIDHD6 = new javax.swing.JLabel();
        TaoHD = new rsbuttom.RSButtonMetro();
        HuyDon = new javax.swing.JButton();
        Order = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        txtTitle = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JLabel();
        txtKichCo = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Img = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        GioHang = new rsbuttom.RSButtonMetro();
        SoLuong = new javax.swing.JSpinner();
        txtGia = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        HuyMon = new rsbuttom.RSButtonMetro();
        CapNhat = new rsbuttom.RSButtonMetro();
        EditDG = new javax.swing.JLabel();
        Edit1 = new javax.swing.JLabel();
        EditSoLuong = new javax.swing.JSpinner();
        EdittxtID1 = new javax.swing.JLabel();
        ThanhToan = new rsbuttom.RSButtonMetro();
        ht1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListOrderSP = new javax.swing.JTable();
        ht2 = new javax.swing.JLabel();
        ht3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTitle1 = new javax.swing.JLabel();
        Category = new javax.swing.JPanel();
        BMKEP = new rsbuttom.RSButtonMetro();
        BKTuoi = new rsbuttom.RSButtonMetro();
        BMTuoi = new rsbuttom.RSButtonMetro();
        BNgot = new rsbuttom.RSButtonMetro();
        BGato = new rsbuttom.RSButtonMetro();
        Pizza = new rsbuttom.RSButtonMetro();
        Drink = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(252, 182, 6));
        jPanel1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thông Tin ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 33)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hoá Đơn");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("IDHD");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Tên Khách Hàng");

        txtIDHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        rSButtonMetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon.png"))); // NOI18N
        rSButtonMetro1.setColorHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro1.setColorNormal(new java.awt.Color(204, 204, 204));
        rSButtonMetro1.setColorPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMetro1MouseClicked(evt);
            }
        });
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Tên Nhân Viên");

        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTenNV.setText("Phạm Hữu Bằng");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Mã Giảm Giá");

        txtSale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSale.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtIDHD4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIDHD4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIDHD4.setText("%");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Tổng Hoá Đơn");

        txtTongHD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTongHD.setText("0.0");

        txtIDHD6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIDHD6.setText("VNĐ");

        TaoHD.setBackground(new java.awt.Color(252, 182, 6));
        TaoHD.setText("Tạo Hoá Đơn");
        TaoHD.setColorHover(new java.awt.Color(255, 153, 0));
        TaoHD.setColorNormal(new java.awt.Color(252, 182, 6));
        TaoHD.setColorPressed(new java.awt.Color(252, 182, 6));
        TaoHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaoHDMouseClicked(evt);
            }
        });
        TaoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaoHDActionPerformed(evt);
            }
        });

        HuyDon.setBackground(new java.awt.Color(252, 182, 6));
        HuyDon.setText("Huỷ Đơn");
        HuyDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HoaDonLayout = new javax.swing.GroupLayout(HoaDon);
        HoaDon.setLayout(HoaDonLayout);
        HoaDonLayout.setHorizontalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addGroup(HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(HoaDonLayout.createSequentialGroup()
                                .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HoaDonLayout.createSequentialGroup()
                                .addGroup(HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(HoaDonLayout.createSequentialGroup()
                                        .addComponent(txtTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIDHD6))
                                    .addGroup(HoaDonLayout.createSequentialGroup()
                                        .addComponent(txtSale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIDHD4))
                                    .addGroup(HoaDonLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtIDHD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(HoaDonLayout.createSequentialGroup()
                        .addGroup(HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HoaDonLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HoaDonLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(TaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HoaDonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(HuyDon)))
                .addContainerGap())
        );
        HoaDonLayout.setVerticalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDHD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSale, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDHD4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongHD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDHD6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(TaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HuyDon)
                .addContainerGap())
        );

        Order.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên Bánh", "Kích cỡ", "Tình Trạng", "Giá Tiền", "Hình Ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 860, 160));

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("Danh Sách Bánh Mỳ Kẹp");
        jPanel4.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 250, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tên Sản Phẩm");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Kích Cỡ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tình Trạng");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Giá Tiền");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("VNĐ/Cái");

        txtID.setText("BMK");

        GioHang.setBackground(new java.awt.Color(252, 182, 6));
        GioHang.setText("Giỏ Hàng");
        GioHang.setColorHover(new java.awt.Color(255, 153, 0));
        GioHang.setColorNormal(new java.awt.Color(252, 182, 6));
        GioHang.setColorPressed(new java.awt.Color(252, 182, 6));
        GioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GioHangActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("IDSP");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Số lượng đặt hàng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(Img, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SoLuong)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(GioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Img, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 860, 250));

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        HuyMon.setBackground(new java.awt.Color(252, 182, 6));
        HuyMon.setText("Huỷ Món");
        HuyMon.setColorHover(new java.awt.Color(255, 153, 0));
        HuyMon.setColorNormal(new java.awt.Color(252, 182, 6));
        HuyMon.setColorPressed(new java.awt.Color(252, 182, 6));
        HuyMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuyMonActionPerformed(evt);
            }
        });

        CapNhat.setText("Cập Nhật");
        CapNhat.setColorHover(new java.awt.Color(255, 153, 0));
        CapNhat.setColorNormal(new java.awt.Color(252, 182, 6));
        CapNhat.setColorPressed(new java.awt.Color(252, 182, 6));
        CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapNhatActionPerformed(evt);
            }
        });

        EditDG.setText("12.0");

        Edit1.setText("VNĐ/Cái");

        EdittxtID1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EdittxtID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EdittxtID1.setText("BMK");

        ThanhToan.setText("Thanh Toán");
        ThanhToan.setColorHover(new java.awt.Color(255, 153, 0));
        ThanhToan.setColorNormal(new java.awt.Color(252, 182, 6));
        ThanhToan.setColorPressed(new java.awt.Color(252, 182, 6));
        ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThanhToanActionPerformed(evt);
            }
        });

        ht1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ht1.setText("Mã Sản Phẩm");

        ListOrderSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Món Ăn", "Đơn Giá", "Số lượng", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ListOrderSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListOrderSPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListOrderSP);
        if (ListOrderSP.getColumnModel().getColumnCount() > 0) {
            ListOrderSP.getColumnModel().getColumn(0).setMaxWidth(100);
            ListOrderSP.getColumnModel().getColumn(1).setMaxWidth(300);
            ListOrderSP.getColumnModel().getColumn(2).setMaxWidth(150);
            ListOrderSP.getColumnModel().getColumn(3).setMaxWidth(100);
            ListOrderSP.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        ht2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ht2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ht2.setText("Đơn Giá");

        ht3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ht3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ht3.setText("Số Lượng Mua");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(190, 190, 190)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ht1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EdittxtID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(EditDG, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ht2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(HuyMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(EditSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(ht3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(295, 295, 295)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ht1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ht2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ht3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EdittxtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditDG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HuyMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 860, 270));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin Sản Phẩm");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 24));

        txtTitle1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle1.setText("Danh Sách Món Ăn Đã Đặt");
        jPanel4.add(txtTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 250, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OrderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OrderLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Category.setBackground(new java.awt.Color(252, 182, 6));

        BMKEP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BMKEP.setText("Bánh Mì Kẹp");
        BMKEP.setColorHover(new java.awt.Color(255, 153, 0));
        BMKEP.setColorNormal(new java.awt.Color(255, 153, 0));
        BMKEP.setColorPressed(new java.awt.Color(252, 182, 6));
        BMKEP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BMKEPMousePressed(evt);
            }
        });
        BMKEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMKEPActionPerformed(evt);
            }
        });

        BKTuoi.setBackground(new java.awt.Color(252, 182, 6));
        BKTuoi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BKTuoi.setText("Bánh Kem Tươi");
        BKTuoi.setColorHover(new java.awt.Color(252, 182, 6));
        BKTuoi.setColorNormal(new java.awt.Color(252, 182, 6));
        BKTuoi.setColorPressed(new java.awt.Color(252, 182, 6));
        BKTuoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BKTuoiMousePressed(evt);
            }
        });
        BKTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKTuoiActionPerformed(evt);
            }
        });

        BMTuoi.setBackground(new java.awt.Color(252, 182, 6));
        BMTuoi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BMTuoi.setText("Bánh Mì Tươi");
        BMTuoi.setColorHover(new java.awt.Color(252, 182, 6));
        BMTuoi.setColorNormal(new java.awt.Color(252, 182, 6));
        BMTuoi.setColorPressed(new java.awt.Color(252, 182, 6));
        BMTuoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BMTuoiMousePressed(evt);
            }
        });
        BMTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMTuoiActionPerformed(evt);
            }
        });

        BNgot.setBackground(new java.awt.Color(252, 182, 6));
        BNgot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BNgot.setText("Bánh Ngọt");
        BNgot.setColorHover(new java.awt.Color(252, 182, 6));
        BNgot.setColorNormal(new java.awt.Color(252, 182, 6));
        BNgot.setColorPressed(new java.awt.Color(252, 182, 6));
        BNgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BNgotMousePressed(evt);
            }
        });
        BNgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNgotActionPerformed(evt);
            }
        });

        BGato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BGato.setText("Bánh Gato");
        BGato.setColorHover(new java.awt.Color(255, 153, 0));
        BGato.setColorNormal(new java.awt.Color(252, 182, 6));
        BGato.setColorPressed(new java.awt.Color(252, 182, 6));
        BGato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BGatoMousePressed(evt);
            }
        });
        BGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGatoActionPerformed(evt);
            }
        });

        Pizza.setBackground(new java.awt.Color(252, 182, 6));
        Pizza.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Pizza.setText("Bánh Pizza");
        Pizza.setColorHover(new java.awt.Color(252, 182, 6));
        Pizza.setColorNormal(new java.awt.Color(252, 182, 6));
        Pizza.setColorPressed(new java.awt.Color(252, 182, 6));
        Pizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PizzaMousePressed(evt);
            }
        });
        Pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaActionPerformed(evt);
            }
        });

        Drink.setBackground(new java.awt.Color(252, 182, 6));
        Drink.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Drink.setText("Đồ Uống");
        Drink.setColorHover(new java.awt.Color(252, 182, 6));
        Drink.setColorNormal(new java.awt.Color(252, 182, 6));
        Drink.setColorPressed(new java.awt.Color(252, 182, 6));
        Drink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DrinkMousePressed(evt);
            }
        });
        Drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CategoryLayout = new javax.swing.GroupLayout(Category);
        Category.setLayout(CategoryLayout);
        CategoryLayout.setHorizontalGroup(
            CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BMKEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BKTuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(BMTuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BNgot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BGato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Drink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CategoryLayout.setVerticalGroup(
            CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BMKEP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BKTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BMTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BNgot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BGato, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Drink, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BMKEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMKEPActionPerformed
        if(this.BMKEP.isSelected()){
            
            HienThi("BK");
            
            this.BMKEP.setColorNormal(new Color(255,153,0));
            this.BMKEP.setColorHover(new Color(255,153,0));
            this.BMKEP.setColorPressed(new Color(255,153,0));
            
            this.BKTuoi.setColorNormal(new Color(255,153,0));
            this.BKTuoi.setColorHover(new Color(255,153,0));
            this.BKTuoi.setColorPressed(new Color(255,153,0));
            
            this.BMTuoi.setColorNormal(new Color(255,153,0));
            this.BMTuoi.setColorHover(new Color(255,153,0));
            this.BMTuoi.setColorPressed(new Color(255,153,0));
            
            this.BNgot.setColorNormal(new Color(255,153,0));
            this.BNgot.setColorHover(new Color(255,153,0));
            this.BNgot.setColorPressed(new Color(255,153,0));
            
            this.BGato.setColorNormal(new Color(255,153,0));
            this.BGato.setColorHover(new Color(255,153,0));
            this.BGato.setColorPressed(new Color(255,153,0));
            
            this.Pizza.setColorNormal(new Color(255,153,0));
            this.Pizza.setColorHover(new Color(255,153,0));
            this.Pizza.setColorPressed(new Color(255,153,0));
            
            this.Drink.setColorNormal(new Color(255,153,0));
            this.Drink.setColorHover(new Color(255,153,0));
            this.Drink.setColorPressed(new Color(255,153,0));
            
        }else{
            this.BMKEP.setColorNormal(new Color(255,153,0));
            this.BMKEP.setColorHover(new Color(255,153,0));
            this.BMKEP.setColorPressed(new Color(255,153,0));
        }
    }//GEN-LAST:event_BMKEPActionPerformed

    private void BMKEPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMKEPMousePressed
        this.BMKEP.setSelected(true);
        this.BKTuoi.setSelected(false);
        this.BMTuoi.setSelected(false);
        this.BNgot.setSelected(false);
        this.BGato.setSelected(false);
        this.Pizza.setSelected(false);
        this.Drink.setSelected(false);
    }//GEN-LAST:event_BMKEPMousePressed

    private void BKTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKTuoiActionPerformed
        if(this.BKTuoi.isSelected()){
            
            HienThi("BKT");
            
            this.BKTuoi.setColorNormal(new Color(255,153,0));
            this.BKTuoi.setColorHover(new Color(255,153,0));
            this.BKTuoi.setColorPressed(new Color(255,153,0));
            
            this.BMKEP.setColorNormal(new Color(255,153,0));
            this.BMKEP.setColorHover(new Color(255,153,0));
            this.BMKEP.setColorPressed(new Color(255,153,0));
            
            this.BMTuoi.setColorNormal(new Color(255,153,0));
            this.BMTuoi.setColorHover(new Color(255,153,0));
            this.BMTuoi.setColorPressed(new Color(255,153,0));
            
            this.BNgot.setColorNormal(new Color(255,153,0));
            this.BNgot.setColorHover(new Color(255,153,0));
            this.BNgot.setColorPressed(new Color(255,153,0));
            
            this.BGato.setColorNormal(new Color(255,153,0));
            this.BGato.setColorHover(new Color(255,153,0));
            this.BGato.setColorPressed(new Color(255,153,0));
            
            this.Pizza.setColorNormal(new Color(255,153,0));
            this.Pizza.setColorHover(new Color(255,153,0));
            this.Pizza.setColorPressed(new Color(255,153,0));
            
            this.Drink.setColorNormal(new Color(255,153,0));
            this.Drink.setColorHover(new Color(255,153,0));
            this.Drink.setColorPressed(new Color(255,153,0));
            
        }else{
            this.BKTuoi.setColorNormal(new Color(255,153,0));
            this.BKTuoi.setColorHover(new Color(255,153,0));
            this.BKTuoi.setColorPressed(new Color(255,153,0));
        }
    }//GEN-LAST:event_BKTuoiActionPerformed

    private void BKTuoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BKTuoiMousePressed
        this.BMKEP.setSelected(false);
        this.BKTuoi.setSelected(true);
        this.BMTuoi.setSelected(false);
        this.BNgot.setSelected(false);
        this.BGato.setSelected(false);
        this.Pizza.setSelected(false);
        this.Drink.setSelected(false);
    }//GEN-LAST:event_BKTuoiMousePressed

    private void BMTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMTuoiActionPerformed
        if(this.BMTuoi.isSelected()){
            
            HienThi("BMT");
            
            this.BMTuoi.setColorNormal(new Color(255,153,0));
            this.BMTuoi.setColorHover(new Color(255,153,0));
            this.BMTuoi.setColorPressed(new Color(255,153,0));
            
            this.BKTuoi.setColorNormal(new Color(255,153,0));
            this.BKTuoi.setColorHover(new Color(255,153,0));
            this.BKTuoi.setColorPressed(new Color(255,153,0));
            
            this.BMKEP.setColorNormal(new Color(255,153,0));
            this.BMKEP.setColorHover(new Color(255,153,0));
            this.BMKEP.setColorPressed(new Color(255,153,0));
            
            this.BNgot.setColorNormal(new Color(255,153,0));
            this.BNgot.setColorHover(new Color(255,153,0));
            this.BNgot.setColorPressed(new Color(255,153,0));
            
            this.BGato.setColorNormal(new Color(255,153,0));
            this.BGato.setColorHover(new Color(255,153,0));
            this.BGato.setColorPressed(new Color(255,153,0));
            
            this.Pizza.setColorNormal(new Color(255,153,0));
            this.Pizza.setColorHover(new Color(255,153,0));
            this.Pizza.setColorPressed(new Color(255,153,0));
            
            this.Drink.setColorNormal(new Color(255,153,0));
            this.Drink.setColorHover(new Color(255,153,0));
            this.Drink.setColorPressed(new Color(255,153,0));
            
        }else{
            this.BMTuoi.setColorNormal(new Color(255,153,0));
            this.BMTuoi.setColorHover(new Color(255,153,0));
            this.BMTuoi.setColorPressed(new Color(255,153,0));
        }
    }//GEN-LAST:event_BMTuoiActionPerformed

    private void BMTuoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMTuoiMousePressed
        this.BMKEP.setSelected(false);
        this.BKTuoi.setSelected(false);
        this.BMTuoi.setSelected(true);
        this.BNgot.setSelected(false);
        this.BGato.setSelected(false);
        this.Pizza.setSelected(false);
        this.Drink.setSelected(false);
    }//GEN-LAST:event_BMTuoiMousePressed

    private void BNgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNgotActionPerformed
        if(this.BNgot.isSelected()){
            
            HienThi("BN");
            
            this.BNgot.setColorNormal(new Color(255,153,0));
            this.BNgot.setColorHover(new Color(255,153,0));
            this.BNgot.setColorPressed(new Color(204,204,204));
            
            this.BKTuoi.setColorNormal(new Color(255,153,0));
            this.BKTuoi.setColorHover(new Color(204,204,204));
            this.BKTuoi.setColorPressed(new Color(204,204,204));
            
            this.BMTuoi.setColorNormal(new Color(255,153,0));
            this.BMTuoi.setColorHover(new Color(255,153,0));
            this.BMTuoi.setColorPressed(new Color(255,153,0));
            
            this.BMKEP.setColorNormal(new Color(255,153,0));
            this.BMKEP.setColorHover(new Color(255,153,0));
            this.BMKEP.setColorPressed(new Color(255,153,0));
            
            this.BGato.setColorNormal(new Color(255,153,0));
            this.BGato.setColorHover(new Color(255,153,0));
            this.BGato.setColorPressed(new Color(255,153,0));
            
            this.Pizza.setColorNormal(new Color(255,153,0));
            this.Pizza.setColorHover(new Color(255,153,0));
            this.Pizza.setColorPressed(new Color(255,153,0));
            
            this.Drink.setColorNormal(new Color(255,153,0));
            this.Drink.setColorHover(new Color(255,153,0));
            this.Drink.setColorPressed(new Color(255,153,0));
            
        }else{
            this.BNgot.setColorNormal(new Color(255,153,0));
            this.BNgot.setColorHover(new Color(255,153,0));
            this.BNgot.setColorPressed(new Color(255,153,0));
        }
    }//GEN-LAST:event_BNgotActionPerformed

    private void BNgotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BNgotMousePressed
        this.BMKEP.setSelected(false);
        this.BKTuoi.setSelected(false);
        this.BMTuoi.setSelected(false);
        this.BNgot.setSelected(true);
        this.BGato.setSelected(false);
        this.Pizza.setSelected(false);
        this.Drink.setSelected(false);
    }//GEN-LAST:event_BNgotMousePressed

    private void BGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGatoActionPerformed
        if(this.BGato.isSelected()){
            
            HienThi("GT");
            
            this.BGato.setColorNormal(new Color(255,153,0));
            this.BGato.setColorHover(new Color(255,153,0));
            this.BGato.setColorPressed(new Color(255,153,0));
            
            this.BKTuoi.setColorNormal(new Color(255,153,0));
            this.BKTuoi.setColorHover(new Color(255,153,0));
            this.BKTuoi.setColorPressed(new Color(255,153,0));
            
            this.BMTuoi.setColorNormal(new Color(255,153,0));
            this.BMTuoi.setColorHover(new Color(255,153,0));
            this.BMTuoi.setColorPressed(new Color(255,153,0));
            
            this.BNgot.setColorNormal(new Color(255,153,0));
            this.BNgot.setColorHover(new Color(255,153,0));
            this.BNgot.setColorPressed(new Color(255,153,0));
            
            this.BMKEP.setColorNormal(new Color(255,153,0));
            this.BMKEP.setColorHover(new Color(255,153,0));
            this.BMKEP.setColorPressed(new Color(255,153,0));
            
            this.Pizza.setColorNormal(new Color(255,153,0));
            this.Pizza.setColorHover(new Color(255,153,0));
            this.Pizza.setColorPressed(new Color(255,153,0));
            
            this.Drink.setColorNormal(new Color(255,153,0));
            this.Drink.setColorHover(new Color(255,153,0));
            this.Drink.setColorPressed(new Color(255,153,0));
            
        }else{
            this.BGato.setColorNormal(new Color(255,153,0));
            this.BGato.setColorHover(new Color(255,153,0));
            this.BGato.setColorPressed(new Color(255,153,0));
        }
    }//GEN-LAST:event_BGatoActionPerformed

    private void BGatoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGatoMousePressed
        this.BMKEP.setSelected(false);
        this.BKTuoi.setSelected(false);
        this.BMTuoi.setSelected(false);
        this.BNgot.setSelected(false);
        this.BGato.setSelected(true);
        this.Pizza.setSelected(false);
        this.Drink.setSelected(false);
    }//GEN-LAST:event_BGatoMousePressed

    private void PizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaActionPerformed
        if(this.Pizza.isSelected()){
            
            HienThi("PZ");
            
            this.Pizza.setColorNormal(new Color(255,153,0));
            this.Pizza.setColorHover(new Color(255,153,0));
            this.Pizza.setColorPressed(new Color(255,153,0));
            
            this.BKTuoi.setColorNormal(new Color(255,153,0));
            this.BKTuoi.setColorHover(new Color(255,153,0));
            this.BKTuoi.setColorPressed(new Color(255,153,0));
            
            this.BMTuoi.setColorNormal(new Color(255,153,0));
            this.BMTuoi.setColorHover(new Color(255,153,0));
            this.BMTuoi.setColorPressed(new Color(255,153,0));
            
            this.BNgot.setColorNormal(new Color(255,153,0));
            this.BNgot.setColorHover(new Color(255,153,0));
            this.BNgot.setColorPressed(new Color(255,153,0));
            
            this.BGato.setColorNormal(new Color(255,153,0));
            this.BGato.setColorHover(new Color(255,153,0));
            this.BGato.setColorPressed(new Color(255,153,0));
            
            this.BMKEP.setColorNormal(new Color(255,153,0));
            this.BMKEP.setColorHover(new Color(255,153,0));
            this.BMKEP.setColorPressed(new Color(255,153,0));
            
            this.Drink.setColorNormal(new Color(255,153,0));
            this.Drink.setColorHover(new Color(255,153,0));
            this.Drink.setColorPressed(new Color(255,153,0));
            
        }else{
            this.Pizza.setColorNormal(new Color(255,153,0));
            this.Pizza.setColorHover(new Color(255,153,0));
            this.Pizza.setColorPressed(new Color(255,153,0));
        }
    }//GEN-LAST:event_PizzaActionPerformed

    private void PizzaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PizzaMousePressed
        this.BMKEP.setSelected(false);
        this.BKTuoi.setSelected(false);
        this.BMTuoi.setSelected(false);
        this.BNgot.setSelected(false);
        this.BGato.setSelected(false);
        this.Pizza.setSelected(true);
        this.Drink.setSelected(false);
    }//GEN-LAST:event_PizzaMousePressed

    private void DrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkActionPerformed
        if(this.Drink.isSelected()){
            
            HienThi("Drink");
            
            this.Drink.setColorNormal(new Color(255,153,0));
            this.Drink.setColorHover(new Color(255,153,0));
            this.Drink.setColorPressed(new Color(255,153,0));
            
            this.BKTuoi.setColorNormal(new Color(255,153,0));
            this.BKTuoi.setColorHover(new Color(255,153,0));
            this.BKTuoi.setColorPressed(new Color(255,153,0));
            
            this.BMTuoi.setColorNormal(new Color(255,153,0));
            this.BMTuoi.setColorHover(new Color(255,153,0));
            this.BMTuoi.setColorPressed(new Color(255,153,0));
            
            this.BNgot.setColorNormal(new Color(255,153,0));
            this.BNgot.setColorHover(new Color(255,153,0));
            this.BNgot.setColorPressed(new Color(255,153,0));
            
            this.BGato.setColorNormal(new Color(255,153,0));
            this.BGato.setColorHover(new Color(255,153,0));
            this.BGato.setColorPressed(new Color(255,153,0));
            
            this.Pizza.setColorNormal(new Color(255,153,0));
            this.Pizza.setColorHover(new Color(255,153,0));
            this.Pizza.setColorPressed(new Color(255,153,0));
            
            this.BMKEP.setColorNormal(new Color(255,153,0));
            this.BMKEP.setColorHover(new Color(255,153,0));
            this.BMKEP.setColorPressed(new Color(255,153,0));
            
        }else{
            this.Drink.setColorNormal(new Color(255,153,0));
            this.Drink.setColorHover(new Color(255,153,0));
            this.Drink.setColorPressed(new Color(2255,153,0));
        }
    }//GEN-LAST:event_DrinkActionPerformed

    private void DrinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrinkMousePressed
        this.BMKEP.setSelected(false);
        this.BKTuoi.setSelected(false);
        this.BMTuoi.setSelected(false);
        this.BNgot.setSelected(false);
        this.BGato.setSelected(false);
        this.Pizza.setSelected(false);
        this.Drink.setSelected(true);
    }//GEN-LAST:event_DrinkMousePressed

    private void TaoHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaoHDMouseClicked
        Category.setVisible(true);
        Order.setVisible(true);
    }//GEN-LAST:event_TaoHDMouseClicked

    private void rSButtonMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro1MouseClicked
       String sdt = JOptionPane.showInputDialog("Nhập sđt");
       ArrayList<sale> list_sale = CustomerController.getList_sale();
       Customer cs = CustomerController.searchCustomer(sdt);
        if (cs != null) {
            String Gia_sale = "";
            txtTenKH.setText(cs.getFullName());
            switch(cs.getCustomerType()){
                case "Gold":
                    for (sale sale : list_sale) {
                        if (sale.getName_rank().endsWith("Gold")) {
                            Gia_sale =(String.valueOf(sale.getSale()));
                        }
                    }
                    txtSale.setText(Gia_sale);
                    break;
                case "Silver":
                    for (sale sale : list_sale) {
                        if (sale.getName_rank().endsWith("Silver")) {
                            Gia_sale =(String.valueOf(sale.getSale()));
                        }
                    }
                    txtSale.setText(Gia_sale);
                    break;
                case "Bronze":
                    for (sale sale : list_sale) {
                        if (sale.getName_rank().endsWith("Bronze")) {
                            Gia_sale =(String.valueOf(sale.getSale()));
                        }
                    }
                    txtSale.setText(Gia_sale);
                    break;
                case "New":
                    for (sale sale : list_sale) {
                        if (sale.getName_rank().endsWith("New")) {
                            Gia_sale =(String.valueOf(sale.getSale()));
                        }
                    }
                    txtSale.setText(Gia_sale);
                    break;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng!");
        }
    }//GEN-LAST:event_rSButtonMetro1MouseClicked

    private void TaoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaoHDActionPerformed
        int idCustomerl = 0;
        String idUser = null;
        for (Customer listCustomer : listCustomers) {
            if (txtTenKH.getText().equals(listCustomer.getFullName())) {
                idCustomerl = Integer.valueOf(listCustomer.getIdCustomer());
                phoneCustomer = listCustomer.getNumberPhone();
            }
        }
        idUser = accountUser.getIdUser();
        Date dNow = new Date( );
        SimpleDateFormat ft = 
        new SimpleDateFormat ("yyyy/MM/dd");
        OrderProduct odProduct = new OrderProduct(idCustomerl, idUser, Integer.valueOf(txtSale.getText()),0.0, ft.format(dNow));
        if (OrderProductController.AddOrder(odProduct) > 0) {
            int idHD = Integer.valueOf(OrderProductController.getListOrder().get(OrderProductController.getListOrder().size()-1).getIdOrder());
            txtIDHD.setText(String.valueOf(idHD));
           
        }else{
            JOptionPane.showMessageDialog(this, "Lỗi tạo mới hoá đơn");
        }
    }//GEN-LAST:event_TaoHDActionPerformed

    private void HuyDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyDonActionPerformed
        dispose();
    }//GEN-LAST:event_HuyDonActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        Object row[] = new Object[6];
        for (int i = 0; i < 6; i++) {
            row[i] = Table.getValueAt(Table.getSelectedRow(), i);
        }
        Product product = new Product(row[0].toString(),row[1].toString(),row[2].toString(),row[3].toString(),Double.valueOf(row[4].toString()), (byte[]) row[5]);
        txtID.setText(product.getIdProduct());
        txtTenSP.setText(product.getNameProduct());
        txtKichCo.setText(product.getSize());
        txtTinhTrang.setText(product.getStatusProduct());
        txtGia.setText(String.valueOf(product.getPriceProduct()));
        byte[] img = product.getAvatar() ;
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(Img.getWidth(),Img.getHeight(), Image.SCALE_SMOOTH));
        Img.setIcon(imageIcon);
    }//GEN-LAST:event_TableMouseClicked

    public void reset_CT(){
        txtTenSP.setText("");
        SoLuong.setValue(0);
        txtKichCo.setText("");
        txtTinhTrang.setText("");
        txtGia.setText("");
        txtID.setText("");
    }
    
    public void HienThiList(){
        DefaultTableModel model_CT = (DefaultTableModel) ListOrderSP.getModel();
        model_CT.setRowCount(0);
        int id = 0;
        String nameProduct = null;
        Double dg = 0.0;
        for (ChiTiet chiTiet1 : listCart) {
            id = id+1;
            for (Product pro : listProduct) {
            if (pro.getIdProduct().equals(chiTiet1.getIdProduct())) {
                dg = pro.getPriceProduct();
                nameProduct = pro.getNameProduct();
            }
        }
            Object[] obj_model = new Object[]{id,nameProduct,dg,chiTiet1.getNumberProduct(),
                chiTiet1.getMoney()
            };
            model_CT.addRow(obj_model);
        }
    }
    
    private void GioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GioHangActionPerformed
        double gia = Double.valueOf(txtGia.getText());
        int number = (int) SoLuong.getValue();
        double price = gia * number;
        Date dNow = new Date( );
        SimpleDateFormat ft = new SimpleDateFormat ("hh:mm:ss");
        ChiTiet ct = new ChiTiet(txtID.getText(),number, price, Integer.valueOf(txtIDHD.getText()) ,ft.format(dNow));
        listCart.add(ct);
        reset_CT();
        HienThiList();
        double total = 0.0;
        for (ChiTiet list : listCart) {
            total = total+list.getMoney();
        }
        txtTongHD.setText(String.valueOf(total));

    }//GEN-LAST:event_GioHangActionPerformed

    private void ListOrderSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListOrderSPMouseClicked
        CapNhat.setVisible(true);
        EditSoLuong.setVisible(true);
        EdittxtID1.setVisible(true);
        EditDG.setVisible(true);
        Edit1.setVisible(true);
        ht1.setVisible(true);
        ht2.setVisible(true);
        ht3.setVisible(true);
        Object row[] = new Object[4];
        for (int i = 0; i < 4; i++) {
            row[i] = ListOrderSP.getValueAt(ListOrderSP.getSelectedRow(), i);
        }
        EditDG.setText(row[2].toString());
        EdittxtID1.setText(row[0].toString());
        EditSoLuong.setValue(row[3]);
    }//GEN-LAST:event_ListOrderSPMouseClicked

    private int round(double d){
        double dAbs = Math.abs(d);
        int i = (int) dAbs;
        double result = dAbs - (double) i;
        if(result<0.5){
            return d<0 ? -i : i;            
        }else{
            return d<0 ? -(i+1) : i+1;          
        }
    }
    
    private void ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThanhToanActionPerformed
        double total = 0.0;
        int idHD = Integer.valueOf(txtIDHD.getText());
        int sale = Integer.valueOf(txtSale.getText());
        for (ChiTiet list : listCart) {
            total = total+list.getMoney();
        }
        double giam = Double.valueOf(sale)/Double.valueOf(100);
        double ThanhToan = round(total- total*giam);
        if (ChiTietController.AddChiTiet(listCart) > 0 && OrderProductController.updateTotal(idHD,ThanhToan)> 0) {
            JOptionPane.showMessageDialog(this, "Tổng tiền thanh toán là "+ ThanhToan);
            for (int i = 0; i < listCart.size(); i++) {
                listCart.remove(i);
            }
            String typeCustomer = null;
            Customer customer = CustomerController.searchCustomer(phoneCustomer);
            double money =  customer.getMoney()+ThanhToan;
            if (money >= 2000.0) {
                    typeCustomer = "Gold";
                }else if (money >= 1000.0 && money < 2000.0 ) {
                        typeCustomer = "Silver";
                    } else if (money >= 500.0 && money < 1000.0 ) {
                            typeCustomer = "Bronze";
                        } else {
                                typeCustomer = "New";
                                } 
                    
            CustomerController.updateCustomer_Money(phoneCustomer, money, typeCustomer);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Hoán đơn lỗi");
            for (int i = 0; i < listCart.size(); i++) {
                listCart.remove(i);
            }
            dispose();
        }
        
    }//GEN-LAST:event_ThanhToanActionPerformed

    private void HuyMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuyMonActionPerformed
        String stt = JOptionPane.showInputDialog("Nhập STT Món");
        listCart.remove(Integer.valueOf(stt)-1);
        HienThiList();
        CapNhat.setVisible(false);
        EditSoLuong.setVisible(false);
        EdittxtID1.setVisible(false);
        EditDG.setVisible(false);
        Edit1.setVisible(false);
    }//GEN-LAST:event_HuyMonActionPerformed

    private void CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapNhatActionPerformed
        int sl = (int) EditSoLuong.getValue();
        double dg = Double.valueOf(EditDG.getText());
        double tong = dg*sl;
        for (int i = 0 ; i < listCart.size(); i++) {
            if (i == Integer.valueOf(EdittxtID1.getText())-1) {
                listCart.get(i).setNumberProduct(sl);
                listCart.get(i).setMoney(tong);
                break;
            }
        }
        HienThiList();
        CapNhat.setVisible(false);
        EditSoLuong.setVisible(false);
        EdittxtID1.setVisible(false);
        EditDG.setVisible(false);
        Edit1.setVisible(false);
        ht1.setVisible(false);
        ht2.setVisible(false);
        ht3.setVisible(false);
    }//GEN-LAST:event_CapNhatActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro BGato;
    private rsbuttom.RSButtonMetro BKTuoi;
    private rsbuttom.RSButtonMetro BMKEP;
    private rsbuttom.RSButtonMetro BMTuoi;
    private rsbuttom.RSButtonMetro BNgot;
    private rsbuttom.RSButtonMetro CapNhat;
    private javax.swing.JPanel Category;
    private rsbuttom.RSButtonMetro Drink;
    private javax.swing.JLabel Edit1;
    private javax.swing.JLabel EditDG;
    private javax.swing.JSpinner EditSoLuong;
    private javax.swing.JLabel EdittxtID1;
    private rsbuttom.RSButtonMetro GioHang;
    private javax.swing.JPanel HoaDon;
    private javax.swing.JButton HuyDon;
    private rsbuttom.RSButtonMetro HuyMon;
    private javax.swing.JLabel Img;
    private javax.swing.JTable ListOrderSP;
    private javax.swing.JPanel Order;
    private rsbuttom.RSButtonMetro Pizza;
    private javax.swing.JSpinner SoLuong;
    private javax.swing.JTable Table;
    private rsbuttom.RSButtonMetro TaoHD;
    private rsbuttom.RSButtonMetro ThanhToan;
    private javax.swing.JLabel ht1;
    private javax.swing.JLabel ht2;
    private javax.swing.JLabel ht3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    private javax.swing.JLabel txtGia;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtIDHD;
    private javax.swing.JLabel txtIDHD4;
    private javax.swing.JLabel txtIDHD6;
    private javax.swing.JLabel txtKichCo;
    private javax.swing.JLabel txtSale;
    private javax.swing.JLabel txtTenKH;
    private javax.swing.JLabel txtTenNV;
    private javax.swing.JLabel txtTenSP;
    private javax.swing.JLabel txtTinhTrang;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtTitle1;
    private javax.swing.JLabel txtTongHD;
    // End of variables declaration//GEN-END:variables
}
