/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Account;
import java.awt.Color;
import java.awt.Image;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;

/**
 *
 * @author Dell G3
 */
public class HomeUser extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    Account accountUser = null;
    
    public HomeUser(){
       initComponents();
        this.setLocationRelativeTo(this);
        this.ThongTin.setSelected(true);
        new CambiaPanel(pnlContent, new View.SanPham.pnlSanPham());
        
        new Thread(){
            public void run(){
                while (true) {                    
                    Calendar ca = new GregorianCalendar();
                    int hour = ca.get(Calendar.HOUR);
                    int minute = ca.get(Calendar.MINUTE);
                    int second = ca.get(Calendar.SECOND);
                    int AM_PM = ca.get(Calendar.AM_PM);
                    
                    String day_night;
                    
                    if (AM_PM == 1) {
                       day_night = "PM"; 
                    }else{
                        day_night = "AM";
                    }
                    String time = hour+":"+minute+":"+second+" "+day_night;
                    labelClock.setText(time);
                }
            }
        }.start();
    }
    
    public HomeUser(Account account) {
        initComponents();
        accountUser = new Account(account.getIdUser(),account.getUserName(),account.getPassWord(),account.getFullName(),account.getPosition(),account.getAge(),account.getEmail(),
        account.getAvatar(),account.getCccd(),account.getAddress(),account.getDate(),account.getSex());
        this.setLocationRelativeTo(this);
        this.ThongTin.setSelected(true);
        new CambiaPanel(pnlContent, new View.User.ThongTin.ViewThongTin(accountUser));
        new Thread(){
            public void run(){
                while (true) {                    
                    Calendar ca = new GregorianCalendar();
                    int hour = ca.get(Calendar.HOUR);
                    int minute = ca.get(Calendar.MINUTE);
                    int second = ca.get(Calendar.SECOND);
                    int AM_PM = ca.get(Calendar.AM_PM);
                    
                    String day_night;
                    
                    if (AM_PM == 1) {
                       day_night = "PM"; 
                    }else{
                        day_night = "AM";
                    }
                    String time = hour+":"+minute+":"+second+" "+day_night;
                    labelClock.setText(time);
                }
            }
        }.start();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new rsbuttom.RSButtonMetro();
        labelClock = new javax.swing.JLabel();
        ptnMenu = new javax.swing.JPanel();
        ThongTin = new rsbuttom.RSButtonMetro();
        KhachHang = new rsbuttom.RSButtonMetro();
        BanHang = new rsbuttom.RSButtonMetro();
        KhoHang = new rsbuttom.RSButtonMetro();
        LogOut = new rsbuttom.RSButtonMetro();
        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(234, 169, 4));

        btnMenu.setBackground(new java.awt.Color(234, 169, 4));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu.png"))); // NOI18N
        btnMenu.setColorBorde(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenu.setColorHover(new java.awt.Color(255, 153, 0));
        btnMenu.setColorNormal(new java.awt.Color(234, 169, 4));
        btnMenu.setColorPressed(new java.awt.Color(234, 169, 4));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        labelClock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelClock.setForeground(new java.awt.Color(255, 255, 255));
        labelClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClock.setText("00:00:00 AM");
        labelClock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                labelClockAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 856, Short.MAX_VALUE)
                .addComponent(labelClock, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(labelClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 60));

        ptnMenu.setBackground(new java.awt.Color(252, 182, 6));
        ptnMenu.setAutoscrolls(true);

        ThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff.png"))); // NOI18N
        ThongTin.setText("THÔNG TIN");
        ThongTin.setColorBorde(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ThongTin.setColorHover(new java.awt.Color(255, 153, 0));
        ThongTin.setColorNormal(new java.awt.Color(252, 182, 6));
        ThongTin.setColorPressed(new java.awt.Color(252, 182, 6));
        ThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThongTinMousePressed(evt);
            }
        });
        ThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongTinActionPerformed(evt);
            }
        });

        KhachHang.setBackground(new java.awt.Color(252, 182, 6));
        KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff1.png"))); // NOI18N
        KhachHang.setText("KHÁCH HÀNG");
        KhachHang.setColorBorde(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KhachHang.setColorHover(new java.awt.Color(255, 153, 0));
        KhachHang.setColorNormal(new java.awt.Color(252, 182, 6));
        KhachHang.setColorPressed(new java.awt.Color(252, 182, 6));
        KhachHang.setFocusTraversalPolicyProvider(true);
        KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KhachHangMousePressed(evt);
            }
        });
        KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachHangActionPerformed(evt);
            }
        });

        BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cart.png"))); // NOI18N
        BanHang.setText("BÁN HÀNG");
        BanHang.setColorBorde(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BanHang.setColorHover(new java.awt.Color(255, 153, 0));
        BanHang.setColorNormal(new java.awt.Color(252, 182, 6));
        BanHang.setColorPressed(new java.awt.Color(252, 182, 6));
        BanHang.setFocusTraversalPolicyProvider(true);
        BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BanHangMousePressed(evt);
            }
        });
        BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanHangActionPerformed(evt);
            }
        });

        KhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/warehouse1.png"))); // NOI18N
        KhoHang.setText("KHO HÀNG");
        KhoHang.setColorBorde(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KhoHang.setColorHover(new java.awt.Color(255, 153, 0));
        KhoHang.setColorNormal(new java.awt.Color(252, 182, 6));
        KhoHang.setColorPressed(new java.awt.Color(252, 182, 6));
        KhoHang.setFocusTraversalPolicyProvider(true);
        KhoHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KhoHangMousePressed(evt);
            }
        });
        KhoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhoHangActionPerformed(evt);
            }
        });

        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout_1.png"))); // NOI18N
        LogOut.setText("ĐĂNG XUẤT");
        LogOut.setColorHover(new java.awt.Color(255, 153, 0));
        LogOut.setColorNormal(new java.awt.Color(252, 182, 6));
        LogOut.setColorPressed(new java.awt.Color(252, 182, 6));
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ptnMenuLayout = new javax.swing.GroupLayout(ptnMenu);
        ptnMenu.setLayout(ptnMenuLayout);
        ptnMenuLayout.setHorizontalGroup(
            ptnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ThongTin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ptnMenuLayout.createSequentialGroup()
                .addGroup(ptnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptnMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ptnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KhoHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        ptnMenuLayout.setVerticalGroup(
            ptnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(ptnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 740));

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new javax.swing.BoxLayout(pnlContent, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 1120, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

    }//GEN-LAST:event_btnMenuActionPerformed

    private void ThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongTinActionPerformed
        if(this.ThongTin.isSelected()){
            new CambiaPanel(pnlContent, new View.User.ThongTin.ViewThongTin(accountUser));
            this.ThongTin.setColorNormal(new Color(255,153,0));
            this.ThongTin.setColorHover(new Color(252,182,6));
            this.ThongTin.setColorPressed(new Color(255,153,0));
            
            this.KhachHang.setColorNormal(new Color(252,182,6));
            this.KhachHang.setColorHover(new Color(252,182,6));
            this.KhachHang.setColorPressed(new Color(252,182,6));
            
            this.BanHang.setColorNormal(new Color(252,182,6));
            this.BanHang.setColorHover(new Color(252,182,6));
            this.BanHang.setColorPressed(new Color(252,182,6));
            
            this.KhoHang.setColorNormal(new Color(252,182,6));
            this.KhoHang.setColorHover(new Color(252,182,6));
            this.KhoHang.setColorPressed(new Color(252,182,6));
            
            
        }else{
            this.ThongTin.setColorNormal(new Color(252,182,6));
            this.ThongTin.setColorHover(new Color(252,182,6));
            this.ThongTin.setColorPressed(new Color(252,182,6));
        }
    }//GEN-LAST:event_ThongTinActionPerformed

    private void ThongTinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongTinMousePressed
        this.ThongTin.setSelected(true);
        this.KhachHang.setSelected(false);
        this.BanHang.setSelected(false);
        this.KhoHang.setSelected(false);
    }//GEN-LAST:event_ThongTinMousePressed

    private void labelClockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_labelClockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_labelClockAncestorAdded

    private void BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanHangActionPerformed
        if(this.BanHang.isSelected()){
            new CambiaPanel(pnlContent, new View.User.BanHang.ViewBanHang(accountUser));
            this.BanHang.setColorNormal(new Color(255,153,0));
            this.BanHang.setColorHover(new Color(252,182,6));
            this.BanHang.setColorPressed(new Color(255,153,0));

            this.KhachHang.setColorNormal(new Color(252,182,6));
            this.KhachHang.setColorHover(new Color(252,182,6));
            this.KhachHang.setColorPressed(new Color(252,182,6));

            this.ThongTin.setColorNormal(new Color(252,182,6));
            this.ThongTin.setColorHover(new Color(252,182,6));
            this.ThongTin.setColorPressed(new Color(252,182,6));

            this.KhoHang.setColorNormal(new Color(252,182,6));
            this.KhoHang.setColorHover(new Color(252,182,6));
            this.KhoHang.setColorPressed(new Color(252,182,6));

        }else{
            this.BanHang.setColorNormal(new Color(252,182,6));
            this.BanHang.setColorHover(new Color(252,182,6));
            this.BanHang.setColorPressed(new Color(252,182,6));
        }
    }//GEN-LAST:event_BanHangActionPerformed

    private void BanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BanHangMousePressed
        this.ThongTin.setSelected(false);
        this.KhachHang.setSelected(false);
        this.BanHang.setSelected(true);
        this.KhoHang.setSelected(false);
    }//GEN-LAST:event_BanHangMousePressed

    private void KhoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhoHangActionPerformed
        if(this.KhoHang.isSelected()){
            new CambiaPanel(pnlContent, new View.User.KhoHang.ViewKhoHang(accountUser));
            this.KhoHang.setColorNormal(new Color(255,153,0));
            this.KhoHang.setColorHover(new Color(252,182,6));
            this.KhoHang.setColorPressed(new Color(255,153,0));

            this.KhachHang.setColorNormal(new Color(252,182,6));
            this.KhachHang.setColorHover(new Color(252,182,6));
            this.KhachHang.setColorPressed(new Color(252,182,6));

            this.ThongTin.setColorNormal(new Color(252,182,6));
            this.ThongTin.setColorHover(new Color(252,182,6));
            this.ThongTin.setColorPressed(new Color(252,182,6));

            this.BanHang.setColorNormal(new Color(252,182,6));
            this.BanHang.setColorHover(new Color(252,182,6));
            this.BanHang.setColorPressed(new Color(252,182,6));

        }else{
            this.KhoHang.setColorNormal(new Color(239,238,244));
            this.KhoHang.setColorHover(new Color(204,204,204));
            this.KhoHang.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_KhoHangActionPerformed

    private void KhoHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhoHangMousePressed
        this.ThongTin.setSelected(false);
        this.KhachHang.setSelected(false);
        this.BanHang.setSelected(false);
        this.KhoHang.setSelected(true);
    }//GEN-LAST:event_KhoHangMousePressed

    private void KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachHangActionPerformed
        if(this.KhachHang.isSelected()){
            new CambiaPanel(pnlContent, new View.User.KhachHang.KhachHang());
            this.KhachHang.setColorNormal(new Color(255,153,0));
            this.KhachHang.setColorHover(new Color(252,182,6));
            this.KhachHang.setColorPressed(new Color(255,153,0));

            this.ThongTin.setColorNormal(new Color(252,182,6));
            this.ThongTin.setColorHover(new Color(252,182,6));
            this.ThongTin.setColorPressed(new Color(252,182,6));

            this.BanHang.setColorNormal(new Color(252,182,6));
            this.BanHang.setColorHover(new Color(252,182,6));
            this.BanHang.setColorPressed(new Color(252,182,6));

            this.KhoHang.setColorNormal(new Color(252,182,6));
            this.KhoHang.setColorHover(new Color(252,182,6));
            this.KhoHang.setColorPressed(new Color(252,182,6));

        }else{
            this.KhachHang.setColorNormal(new Color(252,182,6));
            this.KhachHang.setColorHover(new Color(252,182,6));
            this.KhachHang.setColorPressed(new Color(252,182,6));
        }
    }//GEN-LAST:event_KhachHangActionPerformed

    private void KhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangMousePressed
        this.ThongTin.setSelected(false);
        this.KhachHang.setSelected(true);
        this.BanHang.setSelected(false);
        this.KhoHang.setSelected(false);
    }//GEN-LAST:event_KhachHangMousePressed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro BanHang;
    private rsbuttom.RSButtonMetro KhachHang;
    private rsbuttom.RSButtonMetro KhoHang;
    private rsbuttom.RSButtonMetro LogOut;
    private rsbuttom.RSButtonMetro ThongTin;
    private rsbuttom.RSButtonMetro btnMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelClock;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel ptnMenu;
    // End of variables declaration//GEN-END:variables
}
